apiVersion: v1
kind: Service
metadata:
  name: nextjs-cd
spec:
  type: ClusterIP
  selector:
    app: nextjs-cd
  ports:
    - protocol: TCP
      port: 3000          
      targetPort: 3000  
      containerPort: 3000
